-- =====================================================================
--  The club's real content (team, faculty, earlier projects, past events,
--  Learn videos, contact details) for Supabase.
--
--  Run ONCE, after database_schema.sql:  SQL Editor → New query → paste → Run.
--  Safe to run again: rows that already exist are left as they are.
--  Generated by supabase/make-seed-sql.mjs — edit client/src/data/oldSite.js, not this file.
-- =====================================================================

-- club details
update public.site_settings set club_name = 'AI & Robotics Club',
  tagline = 'Transforming Visions into Reality.',
  email = 'airclub@nitandhra.ac.in',
  phone = '+91 7783847276',
  address = '102, Student Amenities Centre, NIT Andhra Pradesh, Tadepalligudem',
  linkedin = 'https://www.linkedin.com/company/artificial-intelligence-and-robotics-club-nit-andhra-pradesh/about/',
  instagram = 'https://www.instagram.com/ai_and_robotics_nitandhra/',
  youtube = 'https://www.youtube.com/@airclubnitap724',
  mission = 'To cultivate innovation and collaboration among members in exploring artificial intelligence and robotics technologies. Through hands-on projects, we empower members to tackle real-world challenges and drive positive societal impact.'
where id = 1;

-- team and faculty coordinator
insert into public.team_members (id, name, role, "group", department, bio, photo_url, email, linkedin, is_lead, sort_order) values
  ('tm-0', 'Vivek Ranjan', 'Secretary', 'core', null, null, 'https://drive.google.com/thumbnail?id=1P3Zolt3SMD46uYpBPAnQ6W6lqgPnozFq&sz=w500', null, 'https://www.linkedin.com/in/vivek-ranjan-b33769229/', true, 0),
  ('tm-1', 'Kashik Janbandhu', 'Co-Secretary', 'core', null, null, 'https://drive.google.com/thumbnail?id=10ex3ginfCRVepvzVmv0HO-H_s-cgBPeZ&sz=w500', null, 'https://www.linkedin.com/in/kashik-janbandhu-345a7b179/', true, 1),
  ('tm-2', 'Madhav Bhansali', 'Co-Secretary', 'core', null, null, 'https://drive.google.com/thumbnail?id=1rQKVn_MI1DwThs7lXnYHEJy-eIFKqQSE&sz=w500', null, 'https://www.linkedin.com/in/madhav-bhansali-649261252/', true, 2),
  ('tm-3', 'Adyanta Dubey', 'Joint Secretary', 'core', null, null, 'https://drive.google.com/thumbnail?id=1TTeQaDyYafArSwZsU6S7s4u7BP-ilKrH&sz=w500', null, 'https://www.linkedin.com/in/adyanta-dubey-a57895225/', false, 3),
  ('tm-4', 'Mehul Jain', 'Joint Secretary', 'core', null, null, 'https://drive.google.com/thumbnail?id=1PD7ty8BawC-lqkobRs7k8VcNj5GpHpc9&sz=w500', null, 'https://www.linkedin.com/in/mehul-kocheta/', false, 4),
  ('tm-5', 'Jom George', 'Joint Secretary', 'core', null, null, 'https://drive.google.com/thumbnail?id=16VK0kzQ5Ro5dYItccWnTtl5w8fpek4D7&sz=w500', null, 'https://www.linkedin.com/in/jom-george-36318b253/', false, 5),
  ('tm-6', 'G Shweta', 'Head of Management', 'core', null, null, 'https://drive.google.com/thumbnail?id=13wlslxV8tXv5a22GI00X77oKXoOcKve_&sz=w500', null, 'https://www.linkedin.com/in/g-shweta-880104246/', false, 6),
  ('tm-7', 'Krishna Tayal', 'Head of Media and Outreach', 'core', null, null, null, null, 'https://www.linkedin.com/in/krishnataayal/', false, 7),
  ('tm-8', 'Sriya Varshini', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1WXeJDpDmt74JKGhKdxIwviX4WYhAfD8C&sz=w500', null, 'https://www.linkedin.com/in/kasinadhuni-sriya-varshini-114916261/', false, 8),
  ('tm-9', 'Mamidala Anjali', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1J6spp4-x5tb6Pq2BTKYeZTCF1WPUMdmN&sz=w500', null, 'https://www.linkedin.com/in/anjali-mamidala-a8b424234/', false, 9),
  ('tm-10', 'Kasireddy Venkata Sai Satya Pawan Kumar', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1gu3kfzRlq_m6YQrXw2XqliGZSoYYxMwo&sz=w500', null, 'https://www.linkedin.com/in/k-v-s-satya-pawan-kumar/', false, 10),
  ('tm-11', 'Gaurav Chhajed', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1JBpvasXfD4Jxqr-SLXhfT40feK37rxxL&sz=w500', null, 'https://www.linkedin.com/in/gaurav-chhajed/', false, 11),
  ('tm-12', 'Adithya Venkatesh', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=18LdysKShwgQUJh0nkYNrz18qIlOFDm6c&sz=w500', null, 'https://www.linkedin.com/in/artechya/', false, 12),
  ('tm-13', 'Daksh Rao', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1D8RBMQWGc0B64HdnUn6MHh6aV13Uhy8q&sz=w500', null, 'https://www.linkedin.com/in/daksh-r-72329a137/', false, 13),
  ('tm-14', 'Soumyadip Das', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1CzBgcFVLuwCZhels3qnbmJThVRuaj2cj&sz=w500', null, null, false, 14),
  ('tm-15', 'Surojit Das', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1EU_hyOY5APdWFrC69SkU-r2l9haC9mb1&sz=w500', null, 'https://www.linkedin.com/in/surojit-das-b79b77281/', false, 15),
  ('tm-16', 'Shivam Kumar', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1D-T58-uVUvnNUf9PMrRJOf1NxOh6RAmy&sz=w500', null, 'https://www.linkedin.com/in/shivam-kumar-559417290/', false, 16),
  ('tm-17', 'Tangirala Jhansi Reddy', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=19WEDOe0O1tCtlODfkNu7ZTzkb1W7c0yr&sz=w500', null, 'https://www.linkedin.com/in/jhansireddytangirala/', false, 17),
  ('tm-18', 'Vinuthna Ronanki', 'Executive Member', 'executive', null, null, 'https://drive.google.com/thumbnail?id=1Dc2xAEbJRkCI2r9L1DyG1HMno_sLXVHs&sz=w500', null, 'https://www.linkedin.com/in/vinuthna-ronanki-9754012bb/', false, 18),
  ('tm-19', 'Veerla Jahnavi', 'Executive Member', 'executive', null, null, null, null, null, false, 19),
  ('tm-20', 'Shaik Madiha Muskan', 'Executive Member', 'executive', null, null, null, null, null, false, 20),
  ('tm-21', 'Vikas Verma', 'Executive Member', 'executive', null, null, null, null, null, false, 21),
  ('tm-f0', 'Dr. Thella Babu Rao', 'Faculty Coordinator', 'faculty', 'NIT Andhra Pradesh', 'Faculty Coordinator of the AI and Robotics Club.', '/faculty/thella-babu-rao.jpg', 'thellababurao@nitandhra.ac.in', null, false, 100)
on conflict (id) do nothing;

-- earlier projects
insert into public.projects (id, slug, title, summary, description, body, category, status, progress, team_size, tech, archived, image_url, image2_url) values
  ('robotics-arm', 'robotics-arm', 'Robotics Arm', 'A simple, versatile robotic arm for pick-and-place and basic automation tasks.', 'A simple, versatile robotic arm for pick-and-place and basic automation tasks.', 'In this engaging journey, our club designed, assembled, and operated a simple yet effective robotic arm. Our mission was clear: create a versatile robotic arm capable of performing basic tasks, from pick-and-place operations to automation assistance. Collaborative teamwork was central, with each member contributing their unique skills.

Our project presented challenges, including component selection, assembly precision, and streamlined programming. The robotic arm''s debut showcased its simplicity and efficiency. It excelled in various straightforward applications, serving as a foundation for innovation within our club.

Our journey continues as we explore the possibilities of basic robotics, shaping the future of automation.', 'Robotics', 'completed', 100, null, array['Pick-and-place', 'Automation']::text[], true, 'https://drive.google.com/thumbnail?id=19jMp0HrJ60NilyOUaTnML_MUpzNiHzTY&sz=w1000', 'https://drive.google.com/thumbnail?id=1W89hasGYIw6_4197-QH2vrs47nKqDyKh&sz=w1000'),
  ('college-chat-bot', 'college-chat-bot', 'Chat Bot', 'An AI chatbot for the college website, built by a first-year team with machine learning and NLP.', 'An AI chatbot for the college website, built by a first-year team with machine learning and NLP.', 'The chatbot we are making is a college chatbot. Our college website doesn''t have one — that is the motive behind this project.

Our team members are Lokendra, Navya, Shivam, and Jahnavi. All are first-years, and they give their best to the work.

The chatbot is AI based. We are using machine learning, deep learning and NLP to build it, in Python. The bot is adaptable, supporting multiple languages and capable of learning from interactions to improve its performance.

The work is still in progress — about 10% is complete so far, but we expect to make great progress soon.', 'AI / ML', 'in_progress', 10, null, array['Python', 'Machine learning', 'Deep learning', 'NLP']::text[], true, 'https://drive.google.com/thumbnail?id=1lwhwLw2u3JnsO2kpyxfuwNMrE9kf9yTB&sz=w1000', null),
  ('mars-rover', 'mars-rover', 'Mars Rover', 'A versatile, robust rover built to cross rugged terrain — the start of the club’s rover programme.', 'A versatile, robust rover built to cross rugged terrain — the start of the club’s rover programme.', 'Our team is deeply engrossed in a captivating project centered around the development of a cutting-edge rover. This venture underscores our unwavering commitment to pushing the boundaries of technology and exploration, as we endeavor to create a rover capable of navigating diverse and challenging terrains.

Our rover project aspires to craft a versatile, robust rover capable of traversing a spectrum of environments, from rugged Earth landscapes to the potential frontiers of extraterrestrial exploration. The project encompasses meticulous planning, precise engineering, and a deep understanding of the complexities of robotic exploration.

Challenges abound, from mechanical design to electrical systems, autonomous navigation, and scientific instrumentation. Our dedicated team perseveres, addressing each obstacle with creativity and problem-solving acumen, selecting the right components, ensuring robust communication, and advancing autonomous navigation capabilities. Each triumph propels us closer to realizing our vision of pioneering exploration.', 'Robotics', 'in_progress', null, null, array['Mechanical design', 'Electrical systems', 'Autonomous navigation']::text[], true, 'https://drive.google.com/thumbnail?id=1t3dqNB25LAdViGVzmbjtGEF4er8TqFXo&sz=w1000', 'https://drive.google.com/thumbnail?id=13Kt1VzFlwHWJqPcAEBrEUpp66eC2NGXR&sz=w1000'),
  ('micro-mouse', 'micro-mouse', 'Micro Mouse — MazeBlazer', 'A competitive micromouse robot that solves mazes on its own, from Dijkstra to the Partition Central algorithm.', 'A competitive micromouse robot that solves mazes on its own, from Dijkstra to the Partition Central algorithm.', 'This write-up details the design and development of MazeBlazer, a competitive micromouse robot built to conquer complex mazes autonomously: its hardware, its software, and the ongoing optimization work.

## Hardware: balancing performance and size
- Microcontroller: the Arduino Uno R4 is the central processing unit. Its size and power consumption are not ideal for highly competitive micromice, but it is a friendly platform for early development and algorithm testing. Future versions may move to a lower-power microcontroller with on-board ADCs and PWM outputs.
- Motors and encoders: a pair of N20 DC gear motors gives enough torque while keeping the robot compact. Magnetic encoders on the motor shafts report wheel rotations for accurate distance tracking.
- Sensors: Sharp IR sensors detect walls — affordable and easy to integrate, but sensitive to ambient light. Ultrasonic sensors are a possible upgrade.
- Chassis: a lightweight ABS polymer chassis holds everything while keeping weight low, for faster moves and better solve times.

## Software: the brains behind the maze run
- Language: C++, for efficiency and fine control over hardware peripherals.
- Sensor integration: raw voltage readings from the IR sensors are turned into wall presence and distance, with calibration routines for different lighting.
- Motor control: a PID control loop uses encoder feedback to produce smooth, precise movement.

## Version 1: exploring efficiency with Dijkstra
For the first stage we implemented a variant of Dijkstra''s algorithm. It calculates the most efficient connections across the whole maze. It needs the full maze mapped in advance, so it is not suited to real-time competition runs — but it is a solid base for understanding efficient pathfinding, and a benchmark for real-time algorithms.

## Version 2: real-time navigation with Partition Central
Version 2 switches to the Partition Central algorithm, designed for real-time maze exploration.
- Real-time navigation: it guides the robot without pre-exploring, partitioning the maze into smaller sections from sensor data and steering toward the centre of each, eventually reaching the maze centre.
- Adaptability: it adapts to the layout as the robot moves, so it suits different competition mazes.

Dijkstra gives the absolute shortest path through the whole maze; Partition Central favours real-time decisions. Where time limits matter, that can be the more competitive choice even if the path is not always the shortest.

## Continuous improvement
- Sensor testing: rigorous tests with different maze layouts and lighting to find inconsistent readings.
- Algorithm refinement: analysing runs to cut unnecessary turns and reduce solve times.
- Hardware exploration: trying low-power motor drivers better suited to the microcontroller.

MazeBlazer is the result of months of design, development, and testing, pushing miniaturization, sensor integration, and pathfinding. The quest for faster solve times continues.', 'Robotics', 'in_progress', null, null, array['Arduino Uno R4', 'C++', 'PID control', 'IR sensors', 'N20 motors + encoders']::text[], true, null, null),
  ('mini-drone', 'mini-drone', 'Mini Drone', 'Mini drones built from scratch around a Raspberry Pi Pico W instead of an off-the-shelf flight controller.', 'Mini drones built from scratch around a Raspberry Pi Pico W instead of an off-the-shelf flight controller.', 'We are building mini drones from scratch using the Raspberry Pi Pico W instead of default mini-drone controllers like the F3 Evo, so that we can add extra functions to the drone in future.

We are studying the Pico W from its basic operations to its complex capabilities, with week-to-week progress toward every operation a drone controller needs to perform.

## Motive
To build a mini drone that can work just like the large drones.

## Why mini drones?
- Mini drones are becoming increasingly popular and can change the way we interact with our environment. Their small size gives a unique view of the world and reaches places that were previously inaccessible.
- They can do tasks that need precision or difficult manoeuvres in tight spaces.
- They are lightweight, portable, and easy to use, and newer technology has made them more efficient, cost-effective, and reliable.
- They can be used for surveillance, mapping, search-and-rescue, and inspection of infrastructure and buildings — including hazardous places where traditional drones are not suitable.

## Where they are used
- Recreation and entertainment: hobby flying, aerial photography, racing.
- Research and development: robotics, surveillance, agriculture, environmental monitoring.
- Military and defence: reconnaissance, surveillance, tactical operations.
- Humanitarian aid: assessing damage, delivering supplies, search and rescue.
- Innovation: pushing aerodynamics, battery technology, and miniaturization forward.', 'Aerial', 'in_progress', null, null, array['Raspberry Pi Pico W', 'Flight control', 'Embedded']::text[], true, null, null)
on conflict (id) do nothing;

-- past events
insert into public.events (id, title, kind, starts_at, ends_at, venue, description, body, registration_open, capacity, image_url, image2_url, link) values
  ('hackademia-2025', 'Hackademia', 'HACKATHON', '2025-01-24T12:00:00+05:30', '2025-01-25T12:00:00+05:30', 'APJ Abdul Kalam Lab', 'A 24-hour Gen AI hackathon on AI for education.', 'A Gen AI hackathon — Gen AI for Education. 24th and 25th January 2025, from 12 noon for 24 hours.

Join innovators, educators, and students to create AI-driven tools that make learning more accessible, engaging, and impactful in today''s digital age.

## Event tracks
- Track 1: Language Translation and Localization of Educational Content
- Track 2: Accessible Learning Materials for Students with Disabilities
- Track 3: Smart Flowchart and Diagram Generator

## Event highlights
- Innovative solutions for education: participants tackle real-world challenges in education, creating AI-driven tools that make learning more accessible, engaging, and effective.
- Networking and collaboration: a chance to connect with like-minded innovators and entrepreneurs.
- Hands-on learning: participants develop and present AI solutions, with mentorship from experienced faculty members.
- Showcase talent and creativity: a platform for teams to demonstrate their skills and technical expertise.

## Eligibility
- Open to students and scholars from NIT Andhra Pradesh as well as students from other colleges.
- Teams of 2 to 5 members.
- Teams register through the Unstop link and prepare a 2-slide presentation of their approach.

## Format
- Kickoff and team formation: welcome address, introduction, and an overview of the challenge.
- Hacking phase (24 hours): teams pick a track and develop an AI model for it. Mentors are available throughout. Students stay in the event room, and push their updates to a GitHub repository.
- Model evaluation and pitch preparation: teams evaluate their models'' accuracy and performance.

Registration was free.', false, 100, 'https://drive.google.com/thumbnail?id=1D9nVaxcxrqmpyjTkyH4cWb0e64c2PjKi&sz=w1000', 'https://drive.google.com/thumbnail?id=1ftPyc1TY37Md_31oMZxYGKFgG7lUK6vE&sz=w1000', 'https://unstop.com/hackathons/hackademia-2025-national-institute-of-technology-andhra-pradesh-1337149'),
  ('nvidia-ml-workshop-2024', 'Nvidia Workshop — Fundamentals of Machine Learning', 'WORKSHOP', '2024-09-12T09:00:00+05:30', null, 'APJ Abdul Kalam Laboratory Complex', 'A comprehensive, hands-on introduction to machine learning with Keras and TensorFlow.', 'The Fundamental Machine Learning Workshop, organized by the AI and Robotics Club, is a comprehensive introduction to the world of machine learning. It guides participants through the essential concepts and techniques needed to understand and apply machine learning in various contexts.

## What you''ll learn
- Supervised learning: training a model on labeled data, where the algorithm learns from input-output pairs to make predictions on new data.
- Unsupervised learning: working with unlabeled data to find hidden patterns or structures.
- Model evaluation: assessing the performance of models using various metrics, so they are accurate and reliable.
- Feature selection: choosing the most important variables in a dataset — crucial for building efficient models.
- Model deployment: putting machine learning models into real-world applications.
- Algorithm types: including neural networks, the backbone of many modern AI applications.

## Practical experience
Participants don''t just learn theory; they get hands-on experience implementing machine learning algorithms with widely used libraries like Keras and TensorFlow.

## Outcome
By the end of the workshop, participants have a solid understanding of machine learning principles and how to apply them to real-world problems, and a foundation for more advanced topics in machine learning and artificial intelligence.', false, 80, 'https://drive.google.com/thumbnail?id=1INGIZhIby3gqn0wx9qt0NRIo0EbQjF2k&sz=w1000', 'https://drive.google.com/thumbnail?id=1cxC684hqul5BdKUKsOE-tb2VIuXxAdXP&sz=w1000', null),
  ('sih-internal-2024', 'Smart India Internal Hackathon 2024', 'HACKATHON', '2024-09-09T10:00:00+05:30', null, 'NIT Andhra Pradesh, Tadepalligudem', 'The internal selection round for Smart India Hackathon 2024 — top 25 teams go to the national level.', 'NIT Andhra Pradesh hosted the Smart India Internal Hackathon (SIH) 2024, part of the world''s largest innovation challenge. Initiated by the Government of India, SIH gives students a platform to solve real-world problems for government departments and private organizations.

The Internal Hackathon was the selection event for NIT Andhra Pradesh, with the top 25 teams progressing to the national SIH 2024 competition.

## Event highlights
- Participation certificates for all participants.
- 25 teams selected to represent NIT Andhra Pradesh.
- Teams of 6 members, with at least one female student.
- Each team could submit up to 2 ideas; a student could be part of only one team.
- Only the team leader fills out the entry form.

## Why participate?
- Tackle challenges from government and private sector organizations.
- Improve problem-solving and innovation skills through creative collaboration.
- Present solutions to a panel of experts and receive valuable feedback.

## Process
- In college: the Internal Hackathon was organized by the Innovation & Incubation Centre (IIC), the I&E Cell, and the AIR Club. The SPOC, Dr. Sri Phani Krishna Karri, nominated the best 25 ideas for the SIH 2024 portal.
- Outside college: the Government of India screens the ideas and announces finalists, who receive mentoring and training before the SIH Finale.
- After the finale: winning teams receive funding, a stipend, and support to work on their projects for 6 months.', false, 80, 'https://drive.google.com/thumbnail?id=1uQ4OClzUu_W92MoWX7AvUJPhf0NruGFH&sz=w1000', 'https://drive.google.com/thumbnail?id=1gkSvB4RQCV9hZnChwYeFJ1GrmKPqRPC1&sz=w1000', null),
  ('recruitment-2024', 'We Are Hiring — Recruitment Drive 2024', 'RECRUITMENT', '2024-09-09T10:00:00+05:30', null, 'Student Amenity Centre', 'How the club recruits: form, shortlisting, technical check, interview, final selection.', 'Are you captivated by the possibilities of Artificial Intelligence and Robotics? Do you dream of building intelligent systems that could revolutionize industries, or robots that can perform complex tasks? Whether you''re a beginner just starting out or an expert looking to push the boundaries, our club provides the environment for you to grow and excel.

Our community is more than a collection of students — it''s a thriving ecosystem of curious minds dedicated to learning, experimenting, and creating together.

## What we offer
A launchpad for your ideas and a playground for innovation: hands-on projects that range from autonomous robots to intelligent systems.

## Workshops and seminars
We regularly host workshops and seminars led by industry experts and academic leaders. Sessions are interactive, so you not only learn but also apply that knowledge.

## Real-world application
Members take part in national and international competitions and collaborate on ambitious projects. We encourage members to think big, experiment, and take risks.

## Why join us?
You''ll connect with peers who share your passion, gain insights from industry experts, and get access to resources that help you grow personally and professionally.

## Application process
- Form submission: fill out the application form with your background, skills, and interests.
- Resume shortlisting: candidates are shortlisted on academic background, relevant skills, and fit with the club''s objectives.
- Technical skills check: a brief assessment of your knowledge of AI, robotics, and related technologies.
- Interview call: a conversation about your interests, projects, and ideas.
- Final selection: selected candidates officially become members of the AI and Robotics Club.', false, 198, 'https://drive.google.com/thumbnail?id=1Dc6c-SuKYsp4BUOACpGExuMvJ56MtkK1&sz=w1000', 'https://drive.google.com/thumbnail?id=16nGEwQ5P8A0HZ_bz45na5TJ9MXTkSKZx&sz=w1000', null),
  ('robotics-workshop-nugenix-2024', 'Robotics Workshop with Nugenix Robotics', 'TALK', '2024-09-05T09:00:00+05:30', null, 'I&E Cell, NIT Andhra Pradesh', 'Dr. Aditya Marathe, CEO of Nugenix Robotics, on the impact of robotics in industry.', 'Nugenix, the partner and vendor for Kinova Robotics in India, has made remarkable strides in the field of robotics. They have established comprehensive robotics laboratories in engineering institutions in India and worldwide, including IITs, defence laboratories like DRDO, and corporate sectors.

The AI & Robotics Club at NIT Andhra Pradesh had the distinct honour of hosting Dr. Aditya Marathe, the CEO of Nugenix Robotics. The event, conducted in collaboration with E-Yantra and the E & I Cell, gave Dr. Marathe the opportunity to speak about the transformative impact of robotics in industry, and how Nugenix Robotics helps shape the landscape of robotics technology.', false, 120, 'https://drive.google.com/thumbnail?id=1NfFKHraqXpHnR5YVLOzo276PV8azjTG9&sz=w1000', 'https://drive.google.com/thumbnail?id=1ZHLLGF5nXtapJl3A01Qrs8yGLt5hPa8o&sz=w1000', null),
  ('techkriya-2023', 'Techkriya ''23', 'COMPETITION', '2023-11-03T09:00:00+05:30', null, 'MMM Block, NIT Andhra Pradesh', 'The club’s events at the annual Techkriya fest: Micro Mouse, robotic-arm Tic Tac Toe, AR Poster and Cube Solving.', 'In the dynamic realm of technology and innovation, our AI and Robotics Club took centre stage at the annual Techkriya fest held at our college. The club ran a series of events that captivated tech enthusiasts and pushed the boundaries of what is possible in artificial intelligence and robotics.

Creativity, intellect, and technical skill were on show through four events, each designed to challenge participants: the maze-solving of Micro Mouse, Tic Tac Toe played by a robotic arm, augmented reality in the AR Poster event, and the Cube Solving Algorithm challenge.', false, 250, null, 'https://drive.google.com/thumbnail?id=1ZY7aCJScz8r-yhtg0lr0AfdvpHhptyeL&sz=w1000', null),
  ('colloquium-2023', 'Colloquium ''23', 'SHOWCASE', '2023-09-15T09:00:00+05:30', null, 'NIT Andhra Pradesh, Tadepalligudem', 'An Engineers'' Day showcase of research through poster presentations and oral discussions.', 'Colloquium ''23, held on September 15, 2023, at the National Institute of Technology Andhra Pradesh, exceeded all expectations with an immense turnout of participants. The event, dedicated to Engineers'' Day, witnessed an inspiring display of research and innovation from passionate scholars.

Through poster presentations and interactive oral discussions, Colloquium ''23 gave participants a platform to showcase their work and build connections within the engineering community.

We extend our heartfelt thanks to all participants, faculty, and the organizing committee for contributing to the event''s success.', false, 71, 'https://drive.google.com/thumbnail?id=1quFQv6Xn2evRHXlBc32dH2oQ4zL_ovT-&sz=w1000', 'https://drive.google.com/thumbnail?id=1TXTlADFEsYZht_7d1gJyau8U0Va053Vq&sz=w1000', null),
  ('fundamentals-of-deep-learning', 'Fundamentals of Deep Learning', 'WORKSHOP', '2022-01-01T10:00:00+05:30', null, 'NIT Andhra Pradesh, Tadepalligudem', 'A deep learning workshop for 80 selected participants, led by DLI Ambassador Dr. Sri Phani Krishna Karri.', 'With a remarkable response of 164 applicants, we conducted a rigorous selection process, choosing 80 participants who demonstrated outstanding enthusiasm and promising potential.

Guiding us on this journey was our DLI Ambassador, Dr. Sri Phani Krishna Karri. His expertise and passion made the session a dynamic and thought-provoking experience. The workshop became a vibrant hub for exchanging knowledge and developing valuable skills.

We owe a heartfelt thank you to Dr. K. Himabindu, Head of the Department of Computer Science and Engineering at NIT Andhra Pradesh. Her support, with the provision of lab facilities and logistical assistance, played a pivotal role in making this event a success.

This workshop was a testament to the collaborative spirit and dedication of all involved, and an inspiration for future endeavours.', false, 80, 'https://drive.google.com/thumbnail?id=1FSG6YuRdt2VHhEE0ITfQlguLfCu2Ecbl&sz=w1000', 'https://drive.google.com/thumbnail?id=1cjeYO64KQsOClyKn9fW6mEtPMBrwQyS9&sz=w1000', null)
on conflict (id) do nothing;

-- Learn page videos
insert into public.resources (id, title, url, kind, sort_order) values
  ('rs-1', 'What is Artificial Intelligence?', 'https://www.youtube.com/watch?v=c0m6yaGlZh4', 'initial', 0),
  ('rs-2', 'What is Machine Learning?', 'https://www.youtube.com/watch?v=9gGnTQTYNaE', 'initial', 1),
  ('rs-3', 'How deep learning is different?', 'https://www.youtube.com/watch?v=q6kJ71tEYqM', 'initial', 2),
  ('rs-4', 'What is Natural Language Processing?', 'https://www.youtube.com/watch?v=fLvJ8VdHLA0', 'initial', 3),
  ('rs-5', 'What is Generative AI?', 'https://www.youtube.com/watch?v=pWNAtUwnBS8', 'initial', 4),
  ('rs-6', 'Artificial intelligence comes to farming in India | BBC News', 'https://www.youtube.com/watch?v=JeU_EYFH1Jk', 'recent', 5),
  ('rs-7', 'Andrew Ng: Opportunities in AI - 2023', 'https://www.youtube.com/watch?v=5p248yoa3oE', 'recent', 6),
  ('rs-8', 'Google CEO Sundar Pichai and the Future of AI | The Circuit', 'https://www.youtube.com/watch?v=5puu3kN9l7c', 'recent', 7),
  ('rs-9', 'AI art, explained', 'https://www.youtube.com/watch?v=SVcsDDABEkM', 'recent', 8),
  ('rs-10', 'But what is a neural network?', 'https://www.youtube.com/watch?v=aircAruvnKk', 'extra', 9),
  ('rs-11', 'Gradient descent, how neural networks learn', 'https://www.youtube.com/watch?v=IHZwWFHWa-w', 'extra', 10),
  ('rs-12', 'But what is a GPT? Visual intro to transformers', 'https://www.youtube.com/watch?v=wjZofJX0v4M', 'extra', 11),
  ('rs-13', 'Attention in transformers, visually explained', 'https://www.youtube.com/watch?v=eMlx5fFNoYc', 'extra', 12),
  ('rs-14', 'Stanford CS229: Machine Learning Course', 'https://www.youtube.com/watch?v=jGwO_UgTS7I', 'course', 13),
  ('rs-15', 'Stanford CS230: Deep Learning | Autumn 2018', 'https://www.youtube.com/watch?v=PySo_6S4ZAg', 'course', 14),
  ('rs-16', 'Stanford CS224N NLP with Deep Learning', 'https://www.youtube.com/watch?v=LWMzyfvuehA', 'course', 15),
  ('rs-17', 'Stanford CS234: Reinforcement Learning', 'https://www.youtube.com/watch?v=FgzM3zpZ55o', 'course', 16)
on conflict (id) do nothing;
